name: "Label issues"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_description:
    runs-on: ubuntu-22.04
    steps:
      - name: Create labels for issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              color: "B60205",
              name: "bug üêû",
              description: "bugs and defects"
            })
            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              color: "1D76DB",
              name: "docs üìù",
              description: "documentation"
            })
             github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              color: "BFD4F2",
              name: "enhancement üíØ",
              description: "improving already existing features"
            })
             github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              color: "C2E0C6",
              name: "EPIC ‚õ∞",
              description: "epic containing multiple user stories"
            })
             github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              color: "0E8A16",
              name: "feature ü§å",
              description: "new features"
            })
             github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              color: "FEF2C0",
              name: "refactoring ‚å®Ô∏è",
              description: "code refactoring and improvement"
            })
            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              color: "D93F0B",
              name: "urgent üö®",
              description: "urgent issues that require work ASAP"
            })
